### PR TITLE
Add archiver

### PR DESCRIPTION
**Pull request by octopusinvitro**
This PR adds the scraped page archiver gem to the scraper.

# Notes to merger

Should be merged after #3 and before #2

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@octopusinvitro please add the checklist to the PRs before assigning them to me. Thanks.

**Comment by octopusinvitro** [comment]
@tmtmtmtm I added the checklist to the PR description

**Review by tmtmtmtm — CHANGES_REQUESTED** [review]
> the url the scraper points to is not working anymore

I don't really understand the point of this change, then. Why add archiving to a scraper for a page that doesn't exist any more?

**Comment by octopusinvitro** [comment]
@tmtmtmtm because it's scraping the last term, which is the default redirection of that non-working link (but then the data gets assigned to the previous term because it is hardcoded).
I'm going to add a new PR to scrape the last two terms correctly.

**Review by tmtmtmtm — CHANGES_REQUESTED** [review]
What this code is doing, and what the PR description says it's doing aren't the same thing…

**Comment by octopusinvitro** [comment]
@tmtmtmtm I've updated the description :+1:

**Review by tmtmtmtm — APPROVED** [review]

**Comment by tmtmtmtm** [comment]
rebased over master to drop the duplicate commits

**Pull request merged**
